/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface OrderBookSwapLogicInterface extends ethers.utils.Interface {
  functions: {
    "allHashes(uint256,uint256)": FunctionFragment;
    "createOrder((address,address,address,uint256,uint256,address,uint256,uint256,uint8,bytes32,bytes32))": FunctionFragment;
    "getMaker(bytes32)": FunctionFragment;
    "getOrders(address,uint256,uint256)": FunctionFragment;
    "hashesOfFromToken(address,uint256,uint256)": FunctionFragment;
    "hashesOfMaker(address,uint256,uint256)": FunctionFragment;
    "hashesOfToToken(address,uint256,uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "numberOfAllHashes()": FunctionFragment;
    "numberOfHashesOfFromToken(address)": FunctionFragment;
    "numberOfHashesOfMaker(address)": FunctionFragment;
    "numberOfHashesOfToToken(address)": FunctionFragment;
    "orderOfHash(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allHashes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumberish;
        amountOutMin: BigNumberish;
        recipient: string;
        deadline: BigNumberish;
        created: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "getMaker", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOrders",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashesOfFromToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashesOfMaker",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashesOfToToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "numberOfAllHashes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfHashesOfFromToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfHashesOfMaker",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfHashesOfToToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "orderOfHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "allHashes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMaker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOrders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashesOfFromToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashesOfMaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashesOfToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfAllHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfHashesOfFromToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfHashesOfMaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfHashesOfToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderOfHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OrderCreated(bytes32,tuple)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OrderCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OrderCreatedEvent = TypedEvent<
  [
    string,
    [
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      number,
      string,
      string
    ] & {
      maker: string;
      fromToken: string;
      toToken: string;
      amountIn: BigNumber;
      amountOutMin: BigNumber;
      recipient: string;
      deadline: BigNumber;
      created: BigNumber;
      v: number;
      r: string;
      s: string;
    }
  ] & {
    hash: string;
    order: [
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      number,
      string,
      string
    ] & {
      maker: string;
      fromToken: string;
      toToken: string;
      amountIn: BigNumber;
      amountOutMin: BigNumber;
      recipient: string;
      deadline: BigNumber;
      created: BigNumber;
      v: number;
      r: string;
      s: string;
    };
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class OrderBookSwapLogic extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: OrderBookSwapLogicInterface;

  functions: {
    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    createOrder(
      order: {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumberish;
        amountOutMin: BigNumberish;
        recipient: string;
        deadline: BigNumberish;
        created: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getMaker(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { maker: string }>;

    getOrders(
      maker: string,
      offset: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          number,
          string,
          string
        ] & {
          maker: string;
          fromToken: string;
          toToken: string;
          amountIn: BigNumber;
          amountOutMin: BigNumber;
          recipient: string;
          deadline: BigNumber;
          created: BigNumber;
          v: number;
          r: string;
          s: string;
        })[]
      ] & {
        orders: ([
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          number,
          string,
          string
        ] & {
          maker: string;
          fromToken: string;
          toToken: string;
          amountIn: BigNumber;
          amountOutMin: BigNumber;
          recipient: string;
          deadline: BigNumber;
          created: BigNumber;
          v: number;
          r: string;
          s: string;
        })[];
      }
    >;

    hashesOfFromToken(
      fromToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    hashesOfMaker(
      maker: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    hashesOfToToken(
      toToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    /**
     * Replace constructor with initialize function for Upgradable Contracts This function will be called only once by the owner
     */
    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<[BigNumber]>;

    numberOfHashesOfFromToken(
      fromToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    numberOfHashesOfMaker(
      maker: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    numberOfHashesOfToToken(
      toToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    orderOfHash(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        number,
        string,
        string
      ] & {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumber;
        amountOutMin: BigNumber;
        recipient: string;
        deadline: BigNumber;
        created: BigNumber;
        v: number;
        r: string;
        s: string;
      }
    >;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allHashes(
    page: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  createOrder(
    order: {
      maker: string;
      fromToken: string;
      toToken: string;
      amountIn: BigNumberish;
      amountOutMin: BigNumberish;
      recipient: string;
      deadline: BigNumberish;
      created: BigNumberish;
      v: BigNumberish;
      r: BytesLike;
      s: BytesLike;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getMaker(hash: BytesLike, overrides?: CallOverrides): Promise<string>;

  getOrders(
    maker: string,
    offset: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      number,
      string,
      string
    ] & {
      maker: string;
      fromToken: string;
      toToken: string;
      amountIn: BigNumber;
      amountOutMin: BigNumber;
      recipient: string;
      deadline: BigNumber;
      created: BigNumber;
      v: number;
      r: string;
      s: string;
    })[]
  >;

  hashesOfFromToken(
    fromToken: string,
    page: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  hashesOfMaker(
    maker: string,
    page: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  hashesOfToToken(
    toToken: string,
    page: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  /**
   * Replace constructor with initialize function for Upgradable Contracts This function will be called only once by the owner
   */
  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns true if the caller is the current owner.
   */
  isOwner(overrides?: CallOverrides): Promise<boolean>;

  numberOfAllHashes(overrides?: CallOverrides): Promise<BigNumber>;

  numberOfHashesOfFromToken(
    fromToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  numberOfHashesOfMaker(
    maker: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  numberOfHashesOfToToken(
    toToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  orderOfHash(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      number,
      string,
      string
    ] & {
      maker: string;
      fromToken: string;
      toToken: string;
      amountIn: BigNumber;
      amountOutMin: BigNumber;
      recipient: string;
      deadline: BigNumber;
      created: BigNumber;
      v: number;
      r: string;
      s: string;
    }
  >;

  /**
   * Returns the address of the current owner.
   */
  owner(overrides?: CallOverrides): Promise<string>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    createOrder(
      order: {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumberish;
        amountOutMin: BigNumberish;
        recipient: string;
        deadline: BigNumberish;
        created: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    getMaker(hash: BytesLike, overrides?: CallOverrides): Promise<string>;

    getOrders(
      maker: string,
      offset: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        number,
        string,
        string
      ] & {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumber;
        amountOutMin: BigNumber;
        recipient: string;
        deadline: BigNumber;
        created: BigNumber;
        v: number;
        r: string;
        s: string;
      })[]
    >;

    hashesOfFromToken(
      fromToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    hashesOfMaker(
      maker: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    hashesOfToToken(
      toToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    /**
     * Replace constructor with initialize function for Upgradable Contracts This function will be called only once by the owner
     */
    initialize(overrides?: CallOverrides): Promise<void>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: CallOverrides): Promise<boolean>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfHashesOfFromToken(
      fromToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfHashesOfMaker(
      maker: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfHashesOfToToken(
      toToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    orderOfHash(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        number,
        string,
        string
      ] & {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumber;
        amountOutMin: BigNumber;
        recipient: string;
        deadline: BigNumber;
        created: BigNumber;
        v: number;
        r: string;
        s: string;
      }
    >;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<string>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OrderCreated(bytes32,tuple)"(
      hash?: BytesLike | null,
      order?: null
    ): TypedEventFilter<
      [
        string,
        [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          number,
          string,
          string
        ] & {
          maker: string;
          fromToken: string;
          toToken: string;
          amountIn: BigNumber;
          amountOutMin: BigNumber;
          recipient: string;
          deadline: BigNumber;
          created: BigNumber;
          v: number;
          r: string;
          s: string;
        }
      ],
      {
        hash: string;
        order: [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          number,
          string,
          string
        ] & {
          maker: string;
          fromToken: string;
          toToken: string;
          amountIn: BigNumber;
          amountOutMin: BigNumber;
          recipient: string;
          deadline: BigNumber;
          created: BigNumber;
          v: number;
          r: string;
          s: string;
        };
      }
    >;

    OrderCreated(
      hash?: BytesLike | null,
      order?: null
    ): TypedEventFilter<
      [
        string,
        [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          number,
          string,
          string
        ] & {
          maker: string;
          fromToken: string;
          toToken: string;
          amountIn: BigNumber;
          amountOutMin: BigNumber;
          recipient: string;
          deadline: BigNumber;
          created: BigNumber;
          v: number;
          r: string;
          s: string;
        }
      ],
      {
        hash: string;
        order: [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          number,
          string,
          string
        ] & {
          maker: string;
          fromToken: string;
          toToken: string;
          amountIn: BigNumber;
          amountOutMin: BigNumber;
          recipient: string;
          deadline: BigNumber;
          created: BigNumber;
          v: number;
          r: string;
          s: string;
        };
      }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createOrder(
      order: {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumberish;
        amountOutMin: BigNumberish;
        recipient: string;
        deadline: BigNumberish;
        created: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getMaker(hash: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getOrders(
      maker: string,
      offset: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashesOfFromToken(
      fromToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashesOfMaker(
      maker: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashesOfToToken(
      toToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Replace constructor with initialize function for Upgradable Contracts This function will be called only once by the owner
     */
    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfHashesOfFromToken(
      fromToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfHashesOfMaker(
      maker: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfHashesOfToToken(
      toToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    orderOfHash(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allHashes(
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createOrder(
      order: {
        maker: string;
        fromToken: string;
        toToken: string;
        amountIn: BigNumberish;
        amountOutMin: BigNumberish;
        recipient: string;
        deadline: BigNumberish;
        created: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getMaker(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrders(
      maker: string,
      offset: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashesOfFromToken(
      fromToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashesOfMaker(
      maker: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashesOfToToken(
      toToken: string,
      page: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Replace constructor with initialize function for Upgradable Contracts This function will be called only once by the owner
     */
    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfAllHashes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfHashesOfFromToken(
      fromToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfHashesOfMaker(
      maker: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfHashesOfToToken(
      toToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    orderOfHash(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
